name: CI/CD Terraform Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - prod

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ENVIRONMENT: ${{ github.ref_name }}

jobs:
  terraform:
    runs-on: ubuntu-22.04
    if: github.ref != 'refs/heads/prod'  # Ensures this only runs for dev and staging

    name: 'Terraform Deploy for ${{ github.ref }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./deployment

      - name: Terraform Fmt
        run: terraform fmt -check
        working-directory: ./deployment

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./deployment

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars.${{ github.ref_name }} -out=main.tfplan
        working-directory: ./deployment

      #- name: Terraform Apply
      #  if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging'
      #  run: terraform apply -auto-approve main.tfplan
      #  working-directory: ./deployment

  deploy_prod:
    if: github.ref == 'refs/heads/prod'  # This job runs only for production
    environment:
      name: production  # This will trigger manual approval for production
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init for Prod
        run: terraform init
        working-directory: ./deployment

      - name: Terraform Fmt
        run: terraform fmt -check
        working-directory: ./deployment

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./deployment

      - name: Terraform Plan for Prod
        run: terraform plan -var-file=terraform.tfvars.${{ github.ref_name }} -out=main.tfplan
        working-directory: ./deployment

      # - name: Terraform Apply for Prod
      #   run: terraform apply -auto-approve main.tfplan
      #   working-directory: ./deployment

