name: PR Validation for Terraform

on:
  pull_request:
    branches:
      - dev
      - staging
      - prod

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ENVIRONMENT: ${{ github.ref_name }}

jobs:
  validate_pr:
    runs-on: ubuntu-22.04
    name: 'Validate Terraform Code in PR'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./deployment

      - name: Terraform Fmt Check
        run: terraform fmt -check
        working-directory: ./deployment

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./deployment

      - name: Tfsec Check
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./deployment
          github_token: ${{ secrets.GITHUB_TOKEN }}
